// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApElDhoailVaJk6W8mDdNE7hPPLwfaDRk',
    appId: '1:102722170830:web:8f0b938936c80ac801059f',
    messagingSenderId: '102722170830',
    projectId: 'instagram-clone-ritikx',
    authDomain: 'instagram-clone-ritikx.firebaseapp.com',
    storageBucket: 'instagram-clone-ritikx.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXIcQcMS4yzxRsM67ikOTI-dJZZjcL6KM',
    appId: '1:102722170830:android:43cbb2b29ebf595101059f',
    messagingSenderId: '102722170830',
    projectId: 'instagram-clone-ritikx',
    storageBucket: 'instagram-clone-ritikx.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp80C3SWAJG17acOyrnhvXzrEgucFGv6I',
    appId: '1:102722170830:ios:0ac498862ef6854601059f',
    messagingSenderId: '102722170830',
    projectId: 'instagram-clone-ritikx',
    storageBucket: 'instagram-clone-ritikx.appspot.com',
    iosClientId: '102722170830-uu1ndaei34p7kfp0642uvol73lljsog4.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp80C3SWAJG17acOyrnhvXzrEgucFGv6I',
    appId: '1:102722170830:ios:0ac498862ef6854601059f',
    messagingSenderId: '102722170830',
    projectId: 'instagram-clone-ritikx',
    storageBucket: 'instagram-clone-ritikx.appspot.com',
    iosClientId: '102722170830-uu1ndaei34p7kfp0642uvol73lljsog4.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
